# Generated by Django 2.1.2 on 2018-10-30 19:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelPatient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('name_for_URL', models.CharField(max_length=256)),
                ('dob', models.CharField(max_length=128)),
                ('dob_parsed', models.DateField(default=datetime.date(9999, 12, 30))),
                ('sex', models.CharField(max_length=128)),
                ('number_of_studies', models.PositiveIntegerField(default=0)),
                ('dose_PKA_complete', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('dose_KAPR_complete', models.DecimalField(decimal_places=2, default=0, max_digits=64)),
                ('deleted', models.BooleanField(default=False)),
                ('mistaken', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequestDateFixed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_back', models.PositiveIntegerField(default=0)),
                ('months_back', models.PositiveIntegerField(default=0)),
                ('full_info', models.TextField(blank=True, default='', max_length=32768)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequestDatePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_before', models.CharField(blank=True, default='', max_length=256)),
                ('date_after', models.CharField(blank=True, default='', max_length=256)),
                ('full_info', models.TextField(blank=True, default='', max_length=32768)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequestName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=15000)),
                ('full_info', models.TextField(blank=True, default='', max_length=32768)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelRequestUIDs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uids', models.CharField(blank=True, default='', max_length=4096)),
                ('full_info', models.TextField(blank=True, default='', max_length=32768)),
                ('priority', models.PositiveIntegerField(default=0)),
                ('ready', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ModelStudyXA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=256)),
                ('institution', models.CharField(default='HUCAM', max_length=256)),
                ('kv', models.IntegerField(default=0)),
                ('study_date', models.CharField(max_length=128)),
                ('study_date_parsed', models.DateField(default=datetime.date(9999, 12, 30))),
                ('study_time', models.CharField(default='000000', max_length=128)),
                ('study_time_parsed', models.DateField(default=datetime.time(0, 0))),
                ('dose_KAPR_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('dose_PKA_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('fluoro_KAPR_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('fluoro_PKA_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('acq_KAPR_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('acq_PKA_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('fluoro_time_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('acq_time_total', models.DecimalField(decimal_places=2, max_digits=64)),
                ('deleted', models.BooleanField(default=False)),
                ('mistaken', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xa_studies', to='dose_app.ModelPatient')),
            ],
        ),
    ]
